services:
  dev:
    build: .
    environment:
      SERVICE_PORT: 8080
      DATABASE_HOST: db-dev
      DATABASE_USER: readwrite_user
      DATABASE_PASSWORD: readwrite_user
      DATABASE_NAME: profile-board-db
    ports:
      - 8080:8080
    depends_on:
      db-dev:
        condition: service_started
    volumes:
      - gradle-cache:/root/.gradle

  db-base:
    image: postgres:17.6
    environment:
      POSTGRES_USER: readwrite_user
      POSTGRES_PASSWORD: readwrite_user
      POSTGRES_DB: profile-board-db
    ports:
      - "5432:5432"

  db-dev:
    extends:
      service: db-base
    volumes:
      - "db-cache:/var/lib/postgresql/data"

volumes:
  gradle-cache:
  db-cache:
