apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
    - name: curl
      image: alpine/curl:8.14.1
      command: ["sh"]
      stdin: true
      tty: true
  nodeSelector:
    karpenter.sh/nodepool: general-purpose
