apiVersion: v1
kind: Service
metadata:
  name: profile-board-service
  namespace: profile-board-ns
spec:
  type: LoadBalancer
  selector:
    app: profile-board
  ports:
    - port: 80
      targetPort: 8080
